//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"MIIBCgKCAQEAmQJpwnH/7OETiyc0Ohdz9r/NPyq6iXRdzQqh7Reyn94DglLHgggSj6PMhpp12ENf1ZBT/gBrm+GBcm9lfPQoEG2QQjZOM6Lacs16SXyP3d105iCf7P6NsgjaI7awvXhvxrE1eXD7/Dzx15cwWNQoy/jeBCs3dM8NxvjVitf0ssADuYw7Qidsp2SC10GeoiTrw4l9Bn7aR42bvDlwU/1bsolFIK4Rns6eZzXkfLvJ+nZrcOruOyFMeHyJXg7YD0Fjduk7Vmy1Q6CrCgYcRiR20KugeVvF+qlthxBBwIMdH/DF9fvNuBEGkjHOZYclSvQUmsvPMOkkQ70+ofXJ4U+dHQIDAQAB")]
        public string BrainTreeClientKey {
            get {
                return ((string)(this["BrainTreeClientKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Central Standard Time")]
        public string TimeZone {
            get {
                return ((string)(this["TimeZone"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CST")]
        public string TimeZoneAbr {
            get {
                return ((string)(this["TimeZoneAbr"]));
            }
        }
    }
}
