
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ApplicantOwnedAnimal
{

    public System.Guid ID { get; set; }

    public System.Guid PersonID { get; set; }

    public string Name { get; set; }

    public string Breed { get; set; }

    public string Gender { get; set; }

    public string AgeMonths { get; set; }

    public string OwnershipLengthMonths { get; set; }

    public bool IsAltered { get; set; }

    public string AlteredReason { get; set; }

    public bool IsHwPrevention { get; set; }

    public string HwPreventionReason { get; set; }

    public bool IsFullyVaccinated { get; set; }

    public string FullyVaccinatedReason { get; set; }

    public bool IsStillOwned { get; set; }

    public string IsStillOwnedReason { get; set; }

    public System.Guid ApplicantID { get; set; }



    public virtual Entity_Person Entity_Person { get; set; }

    public virtual Applicant Applicant { get; set; }

}

}
