//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Users
    {
        public aspnet_Users()
        {
            this.Blog_Comments = new HashSet<Blog_Comments>();
            this.Blog_Comments1 = new HashSet<Blog_Comments>();
            this.Blog_Post = new HashSet<Blog_Post>();
            this.Blog_Post1 = new HashSet<Blog_Post>();
            this.aspnet_Roles = new HashSet<aspnet_Roles>();
            this.LogUserActivities = new HashSet<LogUserActivity>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public string MobileAlias { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual ICollection<Blog_Comments> Blog_Comments { get; set; }
        public virtual ICollection<Blog_Comments> Blog_Comments1 { get; set; }
        public virtual ICollection<Blog_Post> Blog_Post { get; set; }
        public virtual ICollection<Blog_Post> Blog_Post1 { get; set; }
        public virtual Entity_PersonProfile Entity_PersonProfile { get; set; }
        public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual ICollection<LogUserActivity> LogUserActivities { get; set; }
    }
}
