
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Blog_Comments
{

    public Blog_Comments()
    {

        this.Blog_Comments1 = new HashSet<Blog_Comments>();

    }


    public System.Guid ID { get; set; }

    public System.Guid PostID { get; set; }

    public Nullable<System.Guid> ParentCommentID { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsSpam { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string AuthorIP { get; set; }

    public Nullable<System.Guid> ModeratedByUserID { get; set; }

    public Nullable<System.DateTime> ModeratedDate { get; set; }

    public Nullable<System.Guid> AuthorRegisteredUserID { get; set; }

    public string AuthorName { get; set; }

    public string AuthorEmail { get; set; }

    public string AuthorWebsite { get; set; }

    public string Comment { get; set; }



    public virtual ICollection<Blog_Comments> Blog_Comments1 { get; set; }

    public virtual Blog_Comments Blog_Comments2 { get; set; }

    public virtual Blog_Post Blog_Post { get; set; }

}

}
