
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_Addresses
{

    public Entity_Addresses()
    {

        this.Entity_StoreOrder = new HashSet<Entity_StoreOrder>();

        this.Entity_StoreOrder1 = new HashSet<Entity_StoreOrder>();

    }


    public System.Guid ID { get; set; }

    public string Street { get; set; }

    public string Street2 { get; set; }

    public string City { get; set; }

    public string StateID { get; set; }

    public string ZIP { get; set; }

    public string Type { get; set; }

    public System.Guid EntityID { get; set; }



    public virtual Entity_Base Entity_Base { get; set; }

    public virtual Enum_UsaStates Enum_UsaStates { get; set; }

    public virtual Enum_AddressType Enum_AddressType { get; set; }

    public virtual ICollection<Entity_StoreOrder> Entity_StoreOrder { get; set; }

    public virtual ICollection<Entity_StoreOrder> Entity_StoreOrder1 { get; set; }

}

}
