
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_StoreCartItem
{

    public System.Guid CartId { get; set; }

    public int Id { get; set; }

    public System.Guid ProductVariantId { get; set; }

    public int Quantity { get; set; }



    public virtual Entity_StoreCart Entity_StoreCart { get; set; }

    public virtual Entity_StoreProductVariant Entity_StoreProductVariant { get; set; }

}

}
