
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_OrganisationContacts
{

    public System.Guid OrganisationID { get; set; }

    public System.Guid PersonID { get; set; }

    public int RoleID { get; set; }



    public virtual Entity_Organisation Entity_Organisation { get; set; }

    public virtual Entity_Person Entity_Person { get; set; }

    public virtual Enum_OrganisationRoles Enum_OrganisationRoles { get; set; }

}

}
