
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_DogIntake
{

    public Entity_DogIntake()
    {

        this.Entity_Dog = new HashSet<Entity_Dog>();

    }


    public System.Guid ID { get; set; }

    public int IntakeStatus { get; set; }

    public string ShelterName { get; set; }

    public string WorkerName { get; set; }

    public string HasUntil { get; set; }

    public string VettingNotes { get; set; }

    public Nullable<bool> HasDhppv { get; set; }

    public Nullable<bool> HasDhlppv { get; set; }

    public Nullable<bool> HasRabies { get; set; }

    public Nullable<bool> HasBordetella { get; set; }

    public Nullable<bool> IsDewormed { get; set; }

    public Nullable<bool> IsHwPositive { get; set; }

    public Nullable<bool> IsAltered { get; set; }

    public Nullable<bool> IsUrgent { get; set; }

    public string FacebookUrl { get; set; }

    public string PetfinderUrl { get; set; }

    public string PetangoUrl { get; set; }

    public string OtherUrl { get; set; }

    public string Comments { get; set; }

    public System.DateTime UpdateTimestamp { get; set; }



    public virtual ICollection<Entity_Dog> Entity_Dog { get; set; }

    public virtual Enum_IntakeStatusType Enum_IntakeStatusType { get; set; }

}

}
