
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_SupplyType
{

    public Entity_SupplyType()
    {

        this.Entity_Supplies = new HashSet<Entity_Supplies>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public string ProductUrl { get; set; }

    public Nullable<decimal> Cost { get; set; }

    public string Notes { get; set; }



    public virtual ICollection<Entity_Supplies> Entity_Supplies { get; set; }

}

}
