
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_EmailAddress
{

    public int ID { get; set; }

    public System.Guid EntityID { get; set; }

    public string Address { get; set; }

    public string Type { get; set; }



    public virtual Entity_Base Entity_Base { get; set; }

    public virtual Enum_EmailType Enum_EmailType { get; set; }

}

}
