
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_StoreShippingMethod
{

    public Entity_StoreShippingMethod()
    {

        this.Entity_StoreShipment = new HashSet<Entity_StoreShipment>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedByUser { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public string UpdatedByUser { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public string DeletedByUser { get; set; }



    public virtual ICollection<Entity_StoreShipment> Entity_StoreShipment { get; set; }

}

}
