
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_StoreProduct
{

    public Entity_StoreProduct()
    {

        this.Entity_StoreProductImage = new HashSet<Entity_StoreProductImage>();

        this.Entity_StoreOptionType = new HashSet<Entity_StoreOptionType>();

        this.Entity_StoreProperty = new HashSet<Entity_StoreProperty>();

        this.Entity_StoreProductVariant = new HashSet<Entity_StoreProductVariant>();

    }


    public System.Guid Id { get; set; }

    public bool IsActive { get; set; }

    public System.Guid CategoryId { get; set; }

    public string Name { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedByUser { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public string UpdatedByUser { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public string DeletedByUser { get; set; }

    public string Description { get; set; }



    public virtual Entity_StoreCategory Entity_StoreCategory { get; set; }

    public virtual ICollection<Entity_StoreProductImage> Entity_StoreProductImage { get; set; }

    public virtual ICollection<Entity_StoreOptionType> Entity_StoreOptionType { get; set; }

    public virtual ICollection<Entity_StoreProperty> Entity_StoreProperty { get; set; }

    public virtual ICollection<Entity_StoreProductVariant> Entity_StoreProductVariant { get; set; }

}

}
