
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_DogPlacement
{

    public System.Guid ID { get; set; }

    public System.Guid DogID { get; set; }

    public System.Guid LocationID { get; set; }

    public Nullable<System.DateTime> DateIn { get; set; }

    public System.DateTime DateOut { get; set; }

    public int Status { get; set; }

    public string Comments { get; set; }



    public virtual Entity_Base Entity_Base { get; set; }

    public virtual Entity_Dog Entity_Dog { get; set; }

    public virtual Enum_DogPlacementType Enum_DogPlacementType { get; set; }

}

}
