
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_StoreOptionType
{

    public Entity_StoreOptionType()
    {

        this.Entity_StoreOptionValue = new HashSet<Entity_StoreOptionValue>();

        this.Entity_StoreProduct = new HashSet<Entity_StoreProduct>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }



    public virtual ICollection<Entity_StoreOptionValue> Entity_StoreOptionValue { get; set; }

    public virtual ICollection<Entity_StoreProduct> Entity_StoreProduct { get; set; }

}

}
