
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_SupplyPlacement
{

    public System.Guid ID { get; set; }

    public System.Guid SupplyID { get; set; }

    public System.DateTime DateIn { get; set; }

    public Nullable<System.DateTime> DateOut { get; set; }

    public Nullable<int> Status { get; set; }

    public System.Guid LocationID { get; set; }

    public string Notes { get; set; }



    public virtual Entity_Base Entity_Base { get; set; }

    public virtual Entity_Supplies Entity_Supplies { get; set; }

    public virtual Enum_SupplyPlacementType Enum_SupplyPlacementType { get; set; }

}

}
