
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_StoreProductVariant
{

    public Entity_StoreProductVariant()
    {

        this.Entity_StoreCartItem = new HashSet<Entity_StoreCartItem>();

        this.Entity_StoreOrderDetail = new HashSet<Entity_StoreOrderDetail>();

        this.Entity_StoreOptionValue = new HashSet<Entity_StoreOptionValue>();

    }


    public System.Guid Id { get; set; }

    public System.Guid ProductId { get; set; }

    public bool IsActive { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public decimal CostPrice { get; set; }

    public decimal Weight { get; set; }

    public Nullable<decimal> ShippingCost { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedByUser { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public string UpdatedByUser { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public string DeletedByUser { get; set; }



    public virtual ICollection<Entity_StoreCartItem> Entity_StoreCartItem { get; set; }

    public virtual ICollection<Entity_StoreOrderDetail> Entity_StoreOrderDetail { get; set; }

    public virtual Entity_StoreProduct Entity_StoreProduct { get; set; }

    public virtual ICollection<Entity_StoreOptionValue> Entity_StoreOptionValue { get; set; }

}

}
