
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_Base
{

    public Entity_Base()
    {

        this.Entity_Addresses = new HashSet<Entity_Addresses>();

        this.Entity_EmailAddress = new HashSet<Entity_EmailAddress>();

        this.Entity_PhoneNumber = new HashSet<Entity_PhoneNumber>();

        this.Entity_Organisation = new HashSet<Entity_Organisation>();

        this.Entity_Person = new HashSet<Entity_Person>();

        this.Entity_DogPlacement = new HashSet<Entity_DogPlacement>();

        this.Entity_SupplyPlacement = new HashSet<Entity_SupplyPlacement>();

        this.Entity_StoreOrder = new HashSet<Entity_StoreOrder>();

        this.Entity_Donation = new HashSet<Entity_Donation>();

    }


    public System.Guid ID { get; set; }

    public string Type { get; set; }

    public bool IsActive { get; set; }

    public Nullable<System.DateTime> DateActive { get; set; }

    public Nullable<System.DateTime> DateInActive { get; set; }

    public bool IsDeleted { get; set; }

    public string Comments { get; set; }

    public bool IsMailable { get; set; }

    public bool IsEmailable { get; set; }

    public string WebsiteUrl { get; set; }



    public virtual ICollection<Entity_Addresses> Entity_Addresses { get; set; }

    public virtual ICollection<Entity_EmailAddress> Entity_EmailAddress { get; set; }

    public virtual ICollection<Entity_PhoneNumber> Entity_PhoneNumber { get; set; }

    public virtual ICollection<Entity_Organisation> Entity_Organisation { get; set; }

    public virtual ICollection<Entity_Person> Entity_Person { get; set; }

    public virtual ICollection<Entity_DogPlacement> Entity_DogPlacement { get; set; }

    public virtual ICollection<Entity_SupplyPlacement> Entity_SupplyPlacement { get; set; }

    public virtual ICollection<Entity_StoreOrder> Entity_StoreOrder { get; set; }

    public virtual ICollection<Entity_Donation> Entity_Donation { get; set; }

}

}
