
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_StoreProductImage
{

    public System.Guid Id { get; set; }

    public System.Guid ProductId { get; set; }

    public string Path { get; set; }

    public string Description { get; set; }



    public virtual Entity_StoreProduct Entity_StoreProduct { get; set; }

}

}
