
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_PersonProfile
{

    public System.Guid UserID { get; set; }

    public Nullable<System.Guid> EntityPersonID { get; set; }

    public bool IsActive { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string Phone { get; set; }



    public virtual Entity_Person Entity_Person { get; set; }

}

}
