
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_Organisation
{

    public Entity_Organisation()
    {

        this.Entity_Dog = new HashSet<Entity_Dog>();

        this.Entity_Dog1 = new HashSet<Entity_Dog>();

        this.Entity_DonationItems = new HashSet<Entity_DonationItems>();

        this.Entity_File = new HashSet<Entity_File>();

        this.Event_Sponsor = new HashSet<Event_Sponsor>();

        this.Enum_OrganisationServices = new HashSet<Enum_OrganisationServices>();

        this.Entity_OrganisationContacts = new HashSet<Entity_OrganisationContacts>();

        this.Events = new HashSet<Event>();

    }


    public System.Guid ID { get; set; }

    public System.Guid BaseID { get; set; }

    public string BusinessName { get; set; }

    public string ContactName { get; set; }

    public string ContactTitle { get; set; }

    public string EIN { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }



    public virtual Entity_Base Entity_Base { get; set; }

    public virtual ICollection<Entity_Dog> Entity_Dog { get; set; }

    public virtual ICollection<Entity_Dog> Entity_Dog1 { get; set; }

    public virtual ICollection<Entity_DonationItems> Entity_DonationItems { get; set; }

    public virtual ICollection<Entity_File> Entity_File { get; set; }

    public virtual Enum_OrganisationType Enum_OrganisationType { get; set; }

    public virtual ICollection<Event_Sponsor> Event_Sponsor { get; set; }

    public virtual ICollection<Enum_OrganisationServices> Enum_OrganisationServices { get; set; }

    public virtual ICollection<Entity_OrganisationContacts> Entity_OrganisationContacts { get; set; }

    public virtual ICollection<Event> Events { get; set; }

}

}
