
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_StoreOptionValue
{

    public Entity_StoreOptionValue()
    {

        this.Entity_StoreProductVariant = new HashSet<Entity_StoreProductVariant>();

    }


    public System.Guid Id { get; set; }

    public System.Guid OptionId { get; set; }

    public string Value { get; set; }



    public virtual Entity_StoreOptionType Entity_StoreOptionType { get; set; }

    public virtual ICollection<Entity_StoreProductVariant> Entity_StoreProductVariant { get; set; }

}

}
