
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_DonationItems
{

    public System.Guid ID { get; set; }

    public Nullable<System.Guid> PersonID { get; set; }

    public Nullable<System.Guid> OrganisationID { get; set; }

    public int Quantity { get; set; }

    public string Name { get; set; }

    public Nullable<decimal> CostPerItem { get; set; }

    public int DonationItemType { get; set; }

    public bool HasBeenReceived { get; set; }

    public Nullable<System.DateTime> DateReceived { get; set; }

    public Nullable<System.Guid> EventID { get; set; }

    public Nullable<int> EventPurposeID { get; set; }



    public virtual Enum_DonationItemType Enum_DonationItemType { get; set; }

    public virtual Enum_EventDonationPurpose Enum_EventDonationPurpose { get; set; }

    public virtual Entity_Organisation Entity_Organisation { get; set; }

    public virtual Entity_Person Entity_Person { get; set; }

    public virtual Event Event { get; set; }

}

}
