
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_Dog
{

    public Entity_Dog()
    {

        this.Entity_DogPlacement = new HashSet<Entity_DogPlacement>();

        this.Entity_File = new HashSet<Entity_File>();

    }


    public System.Guid ID { get; set; }

    public Nullable<int> GroupID { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<bool> IsIntake { get; set; }

    public Nullable<System.Guid> IntakeID { get; set; }

    public string Name { get; set; }

    public string MicrochipID { get; set; }

    public Nullable<System.Guid> MicrochipVendorID { get; set; }

    public string ShelterAnimalID { get; set; }

    public Nullable<System.Guid> ShelterID { get; set; }

    public string TattooID { get; set; }

    public string RegistrationID { get; set; }

    public string RabiesID { get; set; }

    public string OtherID { get; set; }

    public Nullable<System.DateTime> DateIntake { get; set; }

    public Nullable<int> IntakeFromID { get; set; }

    public Nullable<int> InitialActivityID { get; set; }

    public string GenderID { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<int> BreedID { get; set; }

    public Nullable<int> BreedSecondID { get; set; }

    public Nullable<bool> IsMix { get; set; }

    public Nullable<int> SizeID { get; set; }

    public Nullable<decimal> Weight { get; set; }

    public Nullable<int> ColorID { get; set; }

    public Nullable<bool> IsAdoptionReady { get; set; }

    public Nullable<bool> IsSpecialNeeds { get; set; }

    public Nullable<System.DateTime> TimestampLastModify { get; set; }

    public string SpecialNeedsNotes { get; set; }

    public string Description { get; set; }

    public string Biography { get; set; }



    public virtual ICollection<Entity_DogPlacement> Entity_DogPlacement { get; set; }

    public virtual ICollection<Entity_File> Entity_File { get; set; }

    public virtual Entity_DogIntake Entity_DogIntake { get; set; }

    public virtual Entity_Organisation Entity_Organisation { get; set; }

    public virtual Entity_Organisation Entity_Organisation1 { get; set; }

    public virtual Enum_Breed Enum_Breed { get; set; }

    public virtual Enum_Breed Enum_Breed1 { get; set; }

    public virtual Enum_HuskyColor Enum_HuskyColor { get; set; }

    public virtual Enum_HuskySize Enum_HuskySize { get; set; }

    public virtual Enum_InitialActivity Enum_InitialActivity { get; set; }

    public virtual Enum_IntakeFrom Enum_IntakeFrom { get; set; }

}

}
