
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_Donation
{

    public System.Guid Id { get; set; }

    public System.DateTime DateSubmitted { get; set; }

    public System.Guid BaseId { get; set; }

    public string BaseType { get; set; }

    public decimal Amount { get; set; }

    public string PaymentTransactionId { get; set; }

    public string DonorComments { get; set; }



    public virtual Entity_Base Entity_Base { get; set; }

}

}
