
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Entity_StoreShipment
{

    public System.Guid Id { get; set; }

    public System.Guid OrderId { get; set; }

    public System.Guid ShippingMethodId { get; set; }

    public string Status { get; set; }

    public decimal Cost { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public string UpdatedByUser { get; set; }

    public Nullable<System.DateTime> ShippedOn { get; set; }

    public string ShippedByUser { get; set; }



    public virtual Entity_StoreOrder Entity_StoreOrder { get; set; }

    public virtual Entity_StoreShippingMethod Entity_StoreShippingMethod { get; set; }

}

}
