
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Enum_EmailType
{

    public Enum_EmailType()
    {

        this.Entity_EmailAddress = new HashSet<Entity_EmailAddress>();

    }


    public string ID { get; set; }

    public string Value { get; set; }



    public virtual ICollection<Entity_EmailAddress> Entity_EmailAddress { get; set; }

}

}
