
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Enum_IntakeStatusType
{

    public Enum_IntakeStatusType()
    {

        this.Entity_DogIntake = new HashSet<Entity_DogIntake>();

    }


    public int ID { get; set; }

    public string Value { get; set; }



    public virtual ICollection<Entity_DogIntake> Entity_DogIntake { get; set; }

}

}
