
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Enum_OrganisationType
{

    public Enum_OrganisationType()
    {

        this.Entity_Organisation = new HashSet<Entity_Organisation>();

    }


    public string ID { get; set; }

    public string Value { get; set; }



    public virtual ICollection<Entity_Organisation> Entity_Organisation { get; set; }

}

}
