
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Enum_EntityType
{

    public Enum_EntityType()
    {

        this.LogUserActivities = new HashSet<LogUserActivity>();

    }


    public int ID { get; set; }

    public string Value { get; set; }



    public virtual ICollection<LogUserActivity> LogUserActivities { get; set; }

}

}
