
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Enum_EventAttendeeType
{

    public Enum_EventAttendeeType()
    {

        this.Event_Attendee = new HashSet<Event_Attendee>();

    }


    public int ID { get; set; }

    public string Value { get; set; }



    public virtual ICollection<Event_Attendee> Event_Attendee { get; set; }

}

}
