
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Enum_DonationItemType
{

    public Enum_DonationItemType()
    {

        this.Entity_DonationItems = new HashSet<Entity_DonationItems>();

    }


    public int ID { get; set; }

    public string Name { get; set; }



    public virtual ICollection<Entity_DonationItems> Entity_DonationItems { get; set; }

}

}
