
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Event_Sponsor
{

    public Event_Sponsor()
    {

        this.Event_SponsorshipLevel = new HashSet<Event_SponsorshipLevel>();

    }


    public System.Guid ID { get; set; }

    public System.Guid EventID { get; set; }

    public System.DateTime DateAdded { get; set; }

    public bool IsSponsoring { get; set; }

    public Nullable<int> SponsorshipLevel { get; set; }

    public bool IsDonating { get; set; }

    public Nullable<decimal> DonationAmount { get; set; }

    public bool IsDonationRecieved { get; set; }

    public Nullable<System.Guid> OrganisationID { get; set; }

    public Nullable<System.Guid> PersonID { get; set; }

    public bool IsSingageComplete { get; set; }

    public string Comments { get; set; }

    public bool HasLogoBeenReceived { get; set; }

    public string WebsiteUrl { get; set; }



    public virtual Entity_Organisation Entity_Organisation { get; set; }

    public virtual Entity_Person Entity_Person { get; set; }

    public virtual ICollection<Event_SponsorshipLevel> Event_SponsorshipLevel { get; set; }

    public virtual Event Event { get; set; }

}

}
