
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Event
{

    public Event()
    {

        this.Entity_DonationItems = new HashSet<Entity_DonationItems>();

        this.Event_Registration = new HashSet<Event_Registration>();

        this.Event_Sponsor = new HashSet<Event_Sponsor>();

    }


    public System.Guid ID { get; set; }

    public Nullable<System.Guid> OrganisationID { get; set; }

    public Nullable<System.DateTime> DateOfEvent { get; set; }

    public bool IsActive { get; set; }

    public string Type { get; set; }

    public Nullable<decimal> AmountSpent { get; set; }

    public Nullable<decimal> AmountReceived { get; set; }

    public string Name { get; set; }

    public string Purpose { get; set; }

    public string Results { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> StartTime { get; set; }

    public Nullable<System.DateTime> EndTime { get; set; }

    public Nullable<bool> IsAllDay { get; set; }

    public Nullable<bool> IsTicketsSold { get; set; }

    public Nullable<decimal> TicketPrice { get; set; }



    public virtual ICollection<Entity_DonationItems> Entity_DonationItems { get; set; }

    public virtual Entity_Organisation Entity_Organisation { get; set; }

    public virtual Enum_EventType Enum_EventType { get; set; }

    public virtual ICollection<Event_Registration> Event_Registration { get; set; }

    public virtual ICollection<Event_Sponsor> Event_Sponsor { get; set; }

}

}
