
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Event_SponsorshipLevel
{

    public int ID { get; set; }

    public System.Guid SponsorID { get; set; }

    public int SponsorshipLevelType { get; set; }



    public virtual Event_Sponsor Event_Sponsor { get; set; }

    public virtual Event_SponsorshipLevelTypes Event_SponsorshipLevelTypes { get; set; }

}

}
