
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Event_Attendee
{

    public System.Guid ID { get; set; }

    public System.Guid EventRegistrationID { get; set; }

    public Nullable<System.Guid> PersonID { get; set; }

    public Nullable<bool> IsPrimaryContact { get; set; }

    public int AttendeeType { get; set; }



    public virtual Entity_Person Entity_Person { get; set; }

    public virtual Enum_EventAttendeeType Enum_EventAttendeeType { get; set; }

    public virtual Event_Registration Event_Registration { get; set; }

}

}
