//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_RegistrationAttendees
    {
        public System.DateTime DateSubmitted { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<System.DateTime> DateOfEvent { get; set; }
        public Nullable<bool> IsActiveEvent { get; set; }
        public string EventType { get; set; }
        public string EventName { get; set; }
        public System.Guid EventId { get; set; }
        public System.Guid RegistrationId { get; set; }
        public Nullable<System.Guid> OrganisationId { get; set; }
        public string Attendees { get; set; }
    }
}
