
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Event_Registration
{

    public Event_Registration()
    {

        this.Event_Attendee = new HashSet<Event_Attendee>();

    }


    public System.Guid ID { get; set; }

    public System.Guid EventID { get; set; }

    public System.DateTime DateSubmitted { get; set; }

    public Nullable<bool> HasPaid { get; set; }

    public Nullable<int> PaymentMethod { get; set; }

    public string Comments { get; set; }

    public Nullable<decimal> AmountPaid { get; set; }

    public Nullable<int> TicketsBought { get; set; }

    public string PaymentTransactionId { get; set; }



    public virtual ICollection<Event_Attendee> Event_Attendee { get; set; }

    public virtual Event Event { get; set; }

}

}
