

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class HuskyRescueEntities : DbContext
{
    public HuskyRescueEntities()
        : base("name=HuskyRescueEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ApplicantOwnedAnimal> ApplicantOwnedAnimals { get; set; }

    public virtual DbSet<ApplicantVeterinarian> ApplicantVeterinarians { get; set; }

    public virtual DbSet<Entity_Addresses> Entity_Addresses { get; set; }

    public virtual DbSet<Entity_Base> Entity_Base { get; set; }

    public virtual DbSet<Entity_Dog> Entity_Dog { get; set; }

    public virtual DbSet<Entity_DogIntake> Entity_DogIntake { get; set; }

    public virtual DbSet<Entity_DogPlacement> Entity_DogPlacement { get; set; }

    public virtual DbSet<Entity_DonationItems> Entity_DonationItems { get; set; }

    public virtual DbSet<Entity_EmailAddress> Entity_EmailAddress { get; set; }

    public virtual DbSet<Entity_File> Entity_File { get; set; }

    public virtual DbSet<Entity_Organisation> Entity_Organisation { get; set; }

    public virtual DbSet<Entity_Person> Entity_Person { get; set; }

    public virtual DbSet<Entity_PhoneNumber> Entity_PhoneNumber { get; set; }

    public virtual DbSet<Entity_Supplies> Entity_Supplies { get; set; }

    public virtual DbSet<Entity_SupplyPlacement> Entity_SupplyPlacement { get; set; }

    public virtual DbSet<Entity_SupplyType> Entity_SupplyType { get; set; }

    public virtual DbSet<Enum_AddressType> Enum_AddressType { get; set; }

    public virtual DbSet<Enum_Breed> Enum_Breed { get; set; }

    public virtual DbSet<Enum_DogPlacementType> Enum_DogPlacementType { get; set; }

    public virtual DbSet<Enum_DonationItemType> Enum_DonationItemType { get; set; }

    public virtual DbSet<Enum_EmailType> Enum_EmailType { get; set; }

    public virtual DbSet<Enum_EventAttendeeType> Enum_EventAttendeeType { get; set; }

    public virtual DbSet<Enum_EventDonationPurpose> Enum_EventDonationPurpose { get; set; }

    public virtual DbSet<Enum_EventType> Enum_EventType { get; set; }

    public virtual DbSet<Enum_Gender> Enum_Gender { get; set; }

    public virtual DbSet<Enum_HuskyColor> Enum_HuskyColor { get; set; }

    public virtual DbSet<Enum_HuskySize> Enum_HuskySize { get; set; }

    public virtual DbSet<Enum_InitialActivity> Enum_InitialActivity { get; set; }

    public virtual DbSet<Enum_IntakeFrom> Enum_IntakeFrom { get; set; }

    public virtual DbSet<Enum_IntakeStatusType> Enum_IntakeStatusType { get; set; }

    public virtual DbSet<Enum_Misc> Enum_Misc { get; set; }

    public virtual DbSet<Enum_OrganisationRoles> Enum_OrganisationRoles { get; set; }

    public virtual DbSet<Enum_OrganisationServices> Enum_OrganisationServices { get; set; }

    public virtual DbSet<Enum_OrganisationType> Enum_OrganisationType { get; set; }

    public virtual DbSet<Enum_PetDepositCoverage> Enum_PetDepositCoverage { get; set; }

    public virtual DbSet<Enum_PhoneType> Enum_PhoneType { get; set; }

    public virtual DbSet<Enum_ResidenceOwnershipType> Enum_ResidenceOwnershipType { get; set; }

    public virtual DbSet<Enum_ResidenceType> Enum_ResidenceType { get; set; }

    public virtual DbSet<Enum_Skills> Enum_Skills { get; set; }

    public virtual DbSet<Enum_StudentType> Enum_StudentType { get; set; }

    public virtual DbSet<Enum_SupplyPlacementType> Enum_SupplyPlacementType { get; set; }

    public virtual DbSet<Enum_UsaStates> Enum_UsaStates { get; set; }

    public virtual DbSet<Event_Attendee> Event_Attendee { get; set; }

    public virtual DbSet<Event_Registration> Event_Registration { get; set; }

    public virtual DbSet<Event_Sponsor> Event_Sponsor { get; set; }

    public virtual DbSet<Event_SponsorshipLevel> Event_SponsorshipLevel { get; set; }

    public virtual DbSet<Event_SponsorshipLevelTypes> Event_SponsorshipLevelTypes { get; set; }

    public virtual DbSet<Blog_Comments> Blog_Comments { get; set; }

    public virtual DbSet<Blog_Post> Blog_Post { get; set; }

    public virtual DbSet<Blog_Tags> Blog_Tags { get; set; }

    public virtual DbSet<Entity_PersonProfile> Entity_PersonProfile { get; set; }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<Enum_EntityType> Enum_EntityType { get; set; }

    public virtual DbSet<Enum_LogActivityEventType> Enum_LogActivityEventType { get; set; }

    public virtual DbSet<LogUserActivity> LogUserActivities { get; set; }

    public virtual DbSet<Applicant> Applicants { get; set; }

    public virtual DbSet<Entity_OrganisationContacts> Entity_OrganisationContacts { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<System_Config> System_Config { get; set; }

    public virtual DbSet<System_ConfigCategory> System_ConfigCategory { get; set; }

    public virtual DbSet<Entity_StoreCart> Entity_StoreCart { get; set; }

    public virtual DbSet<Entity_StoreCartItem> Entity_StoreCartItem { get; set; }

    public virtual DbSet<Entity_StoreCategory> Entity_StoreCategory { get; set; }

    public virtual DbSet<Entity_StoreOptionType> Entity_StoreOptionType { get; set; }

    public virtual DbSet<Entity_StoreOptionValue> Entity_StoreOptionValue { get; set; }

    public virtual DbSet<Entity_StoreOrder> Entity_StoreOrder { get; set; }

    public virtual DbSet<Entity_StoreOrderDetail> Entity_StoreOrderDetail { get; set; }

    public virtual DbSet<Entity_StorePaymentMethod> Entity_StorePaymentMethod { get; set; }

    public virtual DbSet<Entity_StoreProductImage> Entity_StoreProductImage { get; set; }

    public virtual DbSet<Entity_StoreProperty> Entity_StoreProperty { get; set; }

    public virtual DbSet<Entity_StoreShippingMethod> Entity_StoreShippingMethod { get; set; }

    public virtual DbSet<Entity_StoreProduct> Entity_StoreProduct { get; set; }

    public virtual DbSet<Entity_StorePayment> Entity_StorePayment { get; set; }

    public virtual DbSet<Entity_StoreShipment> Entity_StoreShipment { get; set; }

    public virtual DbSet<Entity_StoreProductVariant> Entity_StoreProductVariant { get; set; }

    public virtual DbSet<Entity_Donation> Entity_Donation { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

}

}

