
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Log
{

    public int Id { get; set; }

    public Nullable<bool> IsVisible { get; set; }

    public Nullable<System.Guid> UpdatedByUserId { get; set; }

    public Nullable<System.DateTime> UpdatedTimeStam { get; set; }

    public System.DateTime TimeStamp { get; set; }

    public string Level { get; set; }

    public string Logger { get; set; }

    public string Message { get; set; }

    public string ExceptionType { get; set; }

    public string Operation { get; set; }

    public string ExceptionMessage { get; set; }

    public string StackTrace { get; set; }

}

}
