
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LogUserActivity
{

    public int ID { get; set; }

    public System.DateTime TimeStamp { get; set; }

    public System.Guid UserID { get; set; }

    public int EventTypeID { get; set; }

    public Nullable<int> EntityTypeID { get; set; }

    public string Note { get; set; }



    public virtual Enum_EntityType Enum_EntityType { get; set; }

    public virtual Enum_LogActivityEventType Enum_LogActivityEventType { get; set; }

}

}
