
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HuskyRescue.Model
{

using System;
    using System.Collections.Generic;
    
public partial class System_Config
{

    public string CategoryName { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

    public string Description { get; set; }



    public virtual System_ConfigCategory System_ConfigCategory { get; set; }

}

}
